### ISSUE TITLE
Right click on DTGuild brings up menu behind tooltip

### ISSUE THREAD

**Issue by Chalsean** [Chalsean/XFaction#234]

**Comment by Zoombara** [comment]
This bug can be fixed by adding the below change to DTGuild to shift the frame [strata ](https://wowpedia.fandom.com/wiki/Frame_Strata) to the same one as the SetItemRef function.

```
_Tooltip:SetFrameStrata("FULLSCREEN_DIALOG")
```
Place just below here https://github.com/Chalsean/XFaction/blob/7195f7296a6a83aa26df79ffa8900700a2efdcbb/XFaction/Core/DataText/DTGuild.lua#L237

**Comment by Chalsean** [comment]
What bug?  The one where the menu is behind the tooltip?  Sorry just read
this email
