### ISSUE TITLE
Multiple LUA Errors on Clean Install of Addon and WOW

### ISSUE THREAD

**Issue by enigma7767** [Chalsean/XFaction#300]
I get 29 to 30 LUA errors on Launch of a fresh install of both WOW and EK Xfaction. Using Latest Version of the addon (3.10.2). It appears that it can not find the libraries but i have confirmed they are in the addon package and in the addon folder. I have tried the addon from curse and wowup. Attached is all the errors in a txt file.

[xfactionLUAerrors.txt](https://github.com/Chalsean/XFaction/files/9816059/xfactionLUAerrors.txt)

**Comment by Chalsean** [comment]
I think I found the problem on that, was a library loading order issue.  If you loaded other addons with it, likely Ace would have loaded properly.  I wasn't see them because I was loading BugSack/BugGrabber.  Appreciate the heads up!

Anywho, I have a fix in 4.0.0 which is the DF build scheduled for release Tuesday.
