### ISSUE TITLE
Recognize tagging in character notes

### ISSUE THREAD

**Issue by Chalsean** [Chalsean/XFaction#318]
Examples:
[XFt:Gravity] in the player notes would mean on team Gravity
[XFa:Chalsean] in the notes would mean it is an alt of Chalsean

**Comment by waggz81** [comment]
I like this but would be better if we can use the team initial (and have it be optional). The note space is quite limited. 

So `[XFa:Waggz]` instead of `[J-ZtH] Waggz` where J is our fake team name to make the alt names work. We try to have most of our raiders in the main guild anyway where the simple `[T]` in a non alt rank works for that designation.

**Comment by Chalsean** [comment]
correct the team would be optional.  it would also free up having to define an alt rank.  essentially if XFa is defined, then it will assume alt and append the name given

**Comment by Chalsean** [comment]
Implemented in 4.2
