### ISSUE TITLE
Chat Channels being swapped places every log

### ISSUE THREAD

**Issue by aevic** [Chalsean/XFaction#334]
All of my chat channels are changing number order since installing this while it's not a huge issue I have to reorganize them every time.

**Comment by Chalsean** [comment]
By default the addon will attempt to move its channel to last.  If you would prefer it to not reorganize, you can disable the option under Options -> XFaction -> Chat -> Channel -> Set Channel To Last.  By disabling, the addon will use whatever channel # the WoW client gives it.

**Comment by aevic** [comment]
I have that setting off and it still is switching my channels.

**Comment by Chalsean** [comment]
try resetting your profile

**Comment by aevic** [comment]
Just did that and relogged and my newcomer chat is 1. and general is 2. while my custom channel is 3 where it actually should be but the other channels continue to get set back to different numbers.

https://i.imgur.com/KGC1DGV.png

Sent a ss to show what I mean. General should be 1. trade is 2. sk is my custom channel 3. and 4. Newcomer Chat

**Comment by Chalsean** [comment]
it is using the channel number assigned to it by the wow client.  unforunately the wow client does not store what channel # you want, only that you want to be in General, Trade, etc.  It assigns #s based on startup sequencing.  which is why it screws things up.

im gathering you want trade chat to be #4 which is currently last.  the addon currently only supports being last or whatever blizzard gives it.  an option would be to join some random channel and disable it, have it as 3.  trade chat can be 4 and the addon 5.  unfortunately im not aware of an addon that will store and ensure channel order based on name
